version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
   
    volumes:
      - .:/app 
     
      - sqlite_data:/app/db
    ports:
      - "8000:8000" 
    environment:
      - SECRET_KEY=${SECRET_KEY} 
      - DEBUG=${DEBUG}           
    
    
    env_file:
       - .env.dev 

volumes:
  sqlite_data: 